import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import dayjs from "dayjs";
import isSameOrAfter from "dayjs/plugin/isSameOrAfter";
import isSameOrBefore from "dayjs/plugin/isSameOrBefore";
import ThemeRegistry from "../../components/ThemeRegistry";
import i18nConfig from "@/i18nConfig";
import initTranslations from "../i18n";
import TranslationProvider from "@/components/TranslationProvider";
import "@/i18nConfig";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Math is Mathing",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // 創建時間比對

  dayjs.extend(isSameOrAfter);
  dayjs.extend(isSameOrBefore);

  const i18nNamespaces = ["common"];
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta
          name="google-adsense-account"
          content="ca-pub-3575797160018144"
        ></meta>
      </head>
      <ThemeRegistry>
        <body className="bg-light-teal">
          <TranslationProvider
            locale={locale}
            resources={resources}
            namespaces={i18nNamespaces}
          >
            <NavBar />
            {children}
          </TranslationProvider>
        </body>
      </ThemeRegistry>
    </html>
  );
}
